PRJ=demod_pid_only1_adc_ram_dac2
  
TCL_LIST = $(PRJ).tcl
CONSTR = $(OSCIMP_DIGITAL_IP)/redpitaya_converters/redpitaya_converters_adc.xdc
CONSTR += $(OSCIMP_DIGITAL_IP)/redpitaya_converters/redpitaya_converters.xdc

-include $(OSCIMP_DIGITAL_IP)/fpga_ip.mk

