BASE_NAME=radar_red
USE_STATIC_LIB+=1
CORE_MODULES_LIST = \
	${OSCIMP_DIGITAL_DRIVER}/data_to_ram_core/data_to_ram_core.ko \
	${OSCIMP_DIGITAL_DRIVER}/fpgagen_core/fpgagen_core.ko \
	${OSCIMP_DIGITAL_DRIVER}/edfb_core/edfb_core.ko \
	${OSCIMP_DIGITAL_DRIVER}/switch_core/switch_core.ko
include $(OSCIMP_DIGITAL_APP)/Makefile.inc
