PRJ=demod_pid1_pidpwm3_vco_only2
  
TCL_LIST = $(PRJ).tcl
CONSTR = $(OSCIMP_DIGITAL_IP)/redpitaya_converters/redpitaya_converters_adc.xdc
CONSTR += $(OSCIMP_DIGITAL_IP)/redpitaya_converters/redpitaya_converters.xdc
CONSTR += pwm_axi_test.xdc

-include $(OSCIMP_DIGITAL_IP)/fpga_ip.mk

