BASE_NAME=adc2dac
CORE_MODULES_LIST = \
	${OSCIMP_DIGITAL_DRIVER}/add_const_core/add_const_core.ko \
	${OSCIMP_DIGITAL_DRIVER}/redpitaya_converters_12_core/redpitaya_converters_12_core.ko
include $(OSCIMP_DIGITAL_APP)/Makefile.inc
