PRJ=double_iq_pid_vco
  
TCL_LIST = $(PRJ).tcl
CONSTR = $(OSCIMP_DIGITAL_IP)/redpitaya_converters/redpitaya_converters.xdc
CONSTR_redpitaya = $(OSCIMP_DIGITAL_IP)/redpitaya_converters/redpitaya_converters_adc.xdc
CONSTR_redpitaya16 = $(OSCIMP_DIGITAL_IP)/redpitaya_converters/redpitaya_converters_adc16.xdc

-include $(OSCIMP_DIGITAL_IP)/fpga_ip.mk

