PRJ=p2id_vco_amp_mod_pid_only
  
TCL_LIST = $(PRJ).tcl
CONSTR = $(OSCIMP_DIGITAL_IP)/redpitaya_converters/redpitaya_converters_adc.xdc
CONSTR += $(OSCIMP_DIGITAL_IP)/redpitaya_converters/redpitaya_converters.xdc

-include $(OSCIMP_DIGITAL_IP)/fpga_ip.mk

