BASE_NAME=nco_perturbation
CORE_MODULES_LIST = \
	${OSCIMP_DIGITAL_DRIVER}/nco_counter_core/nco_counter_core.ko \
	${OSCIMP_DIGITAL_DRIVER}/axi_to_dac_core/axi_to_dac_core.ko
include $(OSCIMP_DIGITAL_APP)/Makefile.inc
