PRJ=double_iq_pid_vco
  
TCL_LIST = $(PRJ).tcl
CONSTR = $(OSCIMP_DIGITAL_IP)/redpitaya_converters_12/redpitaya_converters_12_adc.xdc
CONSTR += $(OSCIMP_DIGITAL_IP)/redpitaya_converters_12/redpitaya_converters_12.xdc

-include $(OSCIMP_DIGITAL_IP)/fpga_ip.mk

